### ISSUE TITLE
[Hugo Migration] Determine navigation elements and styling

### ISSUE THREAD

**Issue by ionlights** [ucfai/ucfai#12]
## Tasks:
- [x] (`🔑Required`) Decide on the navigation elements we should have and need.
- [x] (`🔑Required`) On page scroll, the navigation should transition to the dark grey that's used elsewhere on the site (especially on mobile).
- [x] (`🔑Required`) Update navigation element highlights, based on page we're on (including if in sub-menus, e.g. "Groups > Core" – groups should be highlighted).
